version: '2.0'
services:
  go-cli: 
    container_name: go-cli
    image: golang:stretch
    volumes: 
      - .:/app
    working_dir: /app
    environment:
      # All of your dependencies will be found right here under /app/.go/pkg/mod
      - GOPATH=/app/.go